## no critic (Documentation::PodSpelling)
## no critic (Documentation::RequirePodAtEnd)
## no critic (Documentation::RequirePodSections)

package Git::MoreHooks;

use strict;
use warnings;
use 5.010000;
use utf8;

# ABSTRACT: More plugins (Git hooks) for package Git::Hooks.

# VERSION: generated by DZP::OurPkgVersion

=head1 STATUS

Package Git::MoreHooks is currently being developed so changes in the existing hooks are possible.


=head1 SYNOPSIS

Use package via L<Git::Hooks|Git::Hooks> interface (git config file).

=head1 NOTES

Thanks go to Gustavo Leite de Mendonça Chaves for his
L<Git::Hooks|https://metacpan.org/pod/Git::Hooks> package.

=cut

1;

